---
- name: tomcat automation
  hosts: apache
  become: yes
  become_method: sudo
  roles:
     - apache-setup
     - jdk-setup

- name: Nginx automation
  hosts: nginx
  become: yes
  become_method: sudo
  roles:
    - nginx-setup