---

- name:  Install Apache
  apt:
    name: apache2
    update_cache: yes
    state: latest

- name:  Copy Index Html File
  copy:
    src: apache-setup/files/index.html
    dest: /var/www/html
    mode: '0644'
    remote_src: false
  notify: restart apache

- name:  Start Apache
  service:
    name: apache2
    state: started
