---

- name:  Install Apache
  apt:
    name: apache2
    update_cache: yes
    state: latest

- name:  Copy Index Html File
  copy:
    src: index.html
    dest: /var/www/html
    remote_src: yes
  notify: restart apache

- name:  Start Apache
  service:
    name: apache2
    state: started
