---

- name:  Get Jenkins release
  get_url:
    url: https://pkg.jenkins.io/debian/jenkins.repo
    dest: /etc/apt/jenkins.repo

- name: Import jenkins key from url
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/debian/jenkins.io.key

- name: Install jenkins
  apt:
    name: jenkins
    state: latest

- name: Start jenkins
  ansible.builtin.systemd:
   name: jenkins
   state: started