---

- name:  Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name:  Copy Index Html File
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart nginx

- name:  Start Nginx
  service:
    name: nginx
    state: started