---

- name:  Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: latest

- name:  Copy Index Html File
  copy:
    src: nginx-setup/files/index.html
    dest: /var/www/html
    mode: '0644'
    remote_src: false
  notify: restart nginx

- name:  Start Nginx
  service:
    name: nginx
    state: started